/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
import javax.swing.*;
import java.applet.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;

/**
 *
 * @author User
 */
public class graph extends javax.swing.JFrame{

    public graph() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 437, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 285, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Angsana New", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" Graph");

        jButton1.setText("หน้าหลัก");
        jButton1.setPreferredSize(new java.awt.Dimension(101, 37));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(152, 152, 152)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NewHome home = new NewHome();
        home.setVisible(true);

        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void init() {

    }

    public void paint(Graphics g) {

//ตีนหลัง
        g.setColor(Color.darkGray);
        g.fillArc(405, 255, 75, 100, 0, 180);

        g.setColor(Color.black);
        g.drawLine(450, 305, 450, 280);

        g.setColor(Color.black);
        g.drawLine(455, 305, 455, 280);

        g.setColor(Color.darkGray);
        g.fillArc(200, 255, 75, 100, 0, 180);

        g.setColor(Color.black);
        g.drawLine(230, 305, 230, 280);

        g.setColor(Color.black);
        g.drawLine(225, 305, 225, 280);

//ตัว
        g.setColor(Color.gray);
        g.fillArc(200, -200, 200, 500, 235, 70);

        g.setColor(Color.gray);
        g.fillArc(280, -200, 200, 500, 235, 70);

        g.setColor(Color.gray);
        g.fillRoundRect(300, 100, 80, 200, 90, 90);

        g.setColor(Color.gray);
        g.fillRect(240, 255, 200, 50);

//ตา
        g.setColor(Color.white);
        g.fillArc(285, 140, 55, 50, 0, 360);

        g.setColor(Color.black);
        g.drawArc(285, 140, 55, 50, 0, 360);

        g.setColor(Color.white);
        g.fillArc(340, 140, 55, 50, 0, 360);

        g.setColor(Color.black);
        g.drawArc(340, 140, 55, 50, 0, 360);

//แววตา
        g.setColor(Color.black);
        g.fillArc(310, 155, 15, 20, 0, 360);

        g.setColor(Color.black);
        g.fillArc(350, 155, 15, 20, 0, 360);

//จมูก
        g.setColor(Color.yellow);
        g.fillArc(330, 175, 20, 25, 0, 360);

//หนวด
        g.setColor(Color.black);
        g.drawLine(330, 190, 250, 200);

        g.setColor(Color.black);
        g.drawLine(330, 190, 250, 205);

        g.setColor(Color.black);
        g.drawLine(330, 190, 250, 210);

        g.setColor(Color.black);
        g.drawLine(430, 200, 350, 190);

        g.setColor(Color.black);
        g.drawLine(430, 205, 350, 190);

        g.setColor(Color.black);
        g.drawLine(430, 210, 350, 190);

//ปาก
        g.setColor(Color.black);
        g.fillArc(300, 220, 75, 5, 180, 180);

        g.setColor(Color.black);
        g.drawLine(340, 225, 340, 200);

//ตีนหน้า
        g.setColor(Color.darkGray);
        g.fillArc(340, 268, 55, 75, 0, 180);

        g.setColor(Color.black);
        g.drawLine(365, 305, 365, 290);

        g.setColor(Color.black);
        g.drawLine(370, 305, 370, 290);

        g.setColor(Color.darkGray);
        g.fillArc(290, 268, 55, 75, 0, 180);

        g.setColor(Color.black);
        g.drawLine(320, 305, 320, 290);

        g.setColor(Color.black);
        g.drawLine(325, 305, 325, 290);

//ชื่อ
        Font f1 = new Font("Monotype Corsiva", Font.ITALIC, 50);

        g.setFont(f1);

        g.setColor(Color.red);
        g.drawString("Kitsada Kanna", 160, 490);

        g.setColor(Color.red);
        g.drawString("5411133400011", 165, 530);

        g.setColor(Color.red);
        g.drawString("Cartoon cat naruk....", 130, 570);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new graph().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
