
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Menu2 extends javax.swing.JFrame {
  Connection _connect = null;
    Statement _sql_statment = null;
    int Num1;
    int Num2;
    int Num3;
    int Num4;
    int Num5;
    int Num6;
    int Num7;
    int Num8;
    int Num9;
    static int total;
    static int point;
    /**
     * Creates new form Menu2
     */
    public Menu2() {
        initComponents(); try {
           Class.forName("com.mysql.jdbc.Driver");
            _connect = DriverManager.getConnection("jdbc:mysql://localhost/oop"
                    + "?user=root&password=");

            if (_connect != null) {
                System.out.println("Database Connected.");
            } else {
                System.out.println("Database Connect Failed.");
            }

        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
            System.out.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Numchick = new javax.swing.JTextField();
        Numcheese = new javax.swing.JTextField();
        NumZeed = new javax.swing.JTextField();
        Numpotato = new javax.swing.JTextField();
        NumBerger = new javax.swing.JTextField();
        NumNug = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        telephone1 = new javax.swing.JLabel();
        Allpoint = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Numcola = new javax.swing.JTextField();
        Numpepsi = new javax.swing.JTextField();
        Numwater = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UP TO YOU - Menu");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons.png")));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setPreferredSize(new java.awt.Dimension(732, 768));

        jButton1.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jButton1.setText("ยืนยัน");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(234, 182, 106));

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jLabel8.setText("รายการ");

        jLabel9.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jLabel9.setText("ราคา");

        jLabel10.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jLabel10.setText("จำนวน");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel8)
                .addGap(87, 87, 87)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(26, 26, 26))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel14.setText("ไก่ทอดสูตรต้นตำรับ");

        jLabel15.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel15.setText("ไก่ทอดลาวาชีส");

        jLabel16.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel16.setText("ไก่ทอดแซ่บซี๊ด");

        jLabel17.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel17.setText("เฟรนฟรายส์");

        jLabel18.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel18.setText("เบอร์เกอร์ไก่ทอด");

        jLabel19.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel19.setText("นักเก็ตไก่");

        jLabel23.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel23.setText("60 บาท");

        jLabel24.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel24.setText("100 บาท");

        jLabel25.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel25.setText("80 บาท");

        jLabel26.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel26.setText("45 บาท");

        jLabel27.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel27.setText("79 บาท");

        jLabel28.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel28.setText("35 บาท");

        Numchick.setText("0");
        Numchick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumchickActionPerformed(evt);
            }
        });

        Numcheese.setText("0");

        NumZeed.setText("0");

        Numpotato.setText("0");

        NumBerger.setText("0");

        NumNug.setText("0");
        NumNug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumNugActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(NumBerger, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Numpotato, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumZeed, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Numcheese, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Numchick, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumNug, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel23)
                    .addComponent(Numchick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel24)
                    .addComponent(Numcheese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel25)
                    .addComponent(NumZeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel26)
                    .addComponent(Numpotato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel27)
                    .addComponent(NumBerger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel28)
                    .addComponent(NumNug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jButton2.setText("ส่งรายการอาหาร");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jLabel1.setText("ราคาอาหารทั้งหมด");

        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jLabel2.setText("บาท");

        jPanel2.setBackground(new java.awt.Color(218, 77, 79));

        jLabel29.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 60)); // NOI18N
        jLabel29.setText("MENU");

        jLabel30.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jLabel30.setText("รายการอาหาร");

        jLabel33.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jLabel33.setText("ชื่อ");

        jLabel34.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jLabel34.setText("เบอร์โทรศัพท์");

        jLabel35.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jLabel35.setText("แต้มสะสม");

        jLabel36.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jLabel36.setText("แต้ม");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel37.setText("<<");
        jLabel37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18)
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel34)
                        .addGap(18, 18, 18)
                        .addComponent(telephone1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(Allpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel36))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel30))
                            .addComponent(jLabel29))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telephone1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel34)
                        .addComponent(jLabel35)
                        .addComponent(jLabel36))
                    .addComponent(Allpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(234, 182, 106));

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jLabel5.setText("รายการ");

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jLabel6.setText("ราคา");

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jLabel7.setText("จำนวน");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(51, 51, 51)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(234, 132, 94));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jLabel3.setText("รายการอาหาร");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(131, 131, 131))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel11.setText("โค้ก");

        jLabel12.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel12.setText("เป๊บซี่");

        jLabel13.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel13.setText("น้ำเปล่า");

        jLabel20.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel20.setText("40 บาท");

        jLabel21.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel21.setText("40 บาท");

        jLabel22.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel22.setText("15 บาท");

        Numcola.setText("0");

        Numpepsi.setText("0");

        Numwater.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Numpepsi, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(Numcola)
                    .addComponent(Numwater))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel20)
                    .addComponent(Numcola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel21)
                    .addComponent(Numpepsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel22)
                    .addComponent(Numwater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel31.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jLabel31.setText("แต้มสะสมที่ได้รับ");

        jTextField11.setEnabled(false);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jLabel32.setText("แต้ม");

        jPanel3.setBackground(new java.awt.Color(234, 132, 94));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        jLabel4.setText("รายการเครื่องดื่ม");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(101, 101, 101))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(5, 5, 5)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel32)))
                .addGap(0, 45, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(459, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(712, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NumchickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumchickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumchickActionPerformed

    private void NumNugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumNugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumNugActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          if ((Numchick.getText()).equals("") || !(Numchick.getText()).equals("")) {
                if ((Numchick.getText()).equals("")) {
                    Num1 = 0;
                } else if (!(Numchick.getText()).equals("")) {
                    if ((Numchick.getText()).equals("0")) {
                        Num1 = 0;
                    } else {
                        int Num = Integer.parseInt(Numchick.getText());
                        Num1 = Num * 60;
                        point += 30;
                    }

                }
            }
            if ((Numcheese.getText()).equals("") || !(Numcheese.getText()).equals("")) {
                if ((Numcheese.getText()).equals("")) {
                    Num2 = 0;
                } else if (!(Numcheese.getText()).equals("")) {
                    if ((Numcheese.getText()).equals("0")) {
                        Num2 = 0;
                    } else {
                        int Num = Integer.parseInt(Numcheese.getText());
                        Num2 = Num * 100;
                        point += 30;
                    }
                }
            }
            if ((NumZeed.getText()).equals("") || !(NumZeed.getText()).equals("")) {
                if ((NumZeed.getText()).equals("")) {
                    Num3 = 0;
                } else if (!(NumZeed.getText()).equals("")) {
                    if ((NumZeed.getText()).equals("0")) {
                        Num3 = 0;
                    } else {
                        int Num = Integer.parseInt(NumZeed.getText());
                        Num3 = Num * 80;
                        point += 30;
                    }

                }
            }
            if ((NumNug.getText()).equals("") || !(NumNug.getText()).equals("")) {
                if ((NumNug.getText()).equals("")) {
                    Num4 = 0;
                } else if (!(NumNug.getText()).equals("")) {
                    if ((NumNug.getText()).equals("0")) {
                        Num4 = 0;
                    } else {
                        int Num = Integer.parseInt(NumNug.getText());
                        Num4 = Num * 35;
                        point += 30;
                    }
                }
            }
            if ((Numpotato.getText()).equals("") || !(Numpotato.getText()).equals("")) {
                if ((Numpotato.getText()).equals("")) {
                    Num5 = 0;
                } else if (!(Numpotato.getText()).equals("")) {
                    if ((Numpotato.getText()).equals("0")) {
                        Num5 = 0;
                    } else {
                        int Num = Integer.parseInt(Numpotato.getText());
                        Num5 = Num * 45;
                        point += 30;
                    }

                }
            }
            if ((NumBerger.getText()).equals("") || !(NumBerger.getText()).equals("")) {
                if ((NumBerger.getText()).equals("")) {
                    Num6 = 0;
                } else if (!(NumBerger.getText()).equals("")) {
                    if ((NumBerger.getText()).equals("0")) {
                        Num6 = 0;
                    } else {
                        int Num = Integer.parseInt(NumBerger.getText());
                        Num6 = Num * 79;
                        point += 30;
                    }

                }
            }
            if ((Numcola.getText()).equals("") || !(Numcola.getText()).equals("")) {
                if ((Numcola.getText()).equals("")) {
                    Num7 = 0;
                } else if (!(Numcola.getText()).equals("")) {
                    if ((Numcola.getText()).equals("0")) {
                        Num7 = 0;
                    } else {
                        int Num = Integer.parseInt(Numcola.getText());
                        Num7 = Num * 40;
                        point += 30;
                    }

                }
            }
            if ((Numpepsi.getText()).equals("") || !(Numpepsi.getText()).equals("")) {
                if ((Numpepsi.getText()).equals("")) {
                    Num8 = 0;
                } else if (!(Numpepsi.getText()).equals("")) {
                    if ((Numpepsi.getText()).equals("0")) {
                        Num8 = 0;
                    } else {
                        int Num = Integer.parseInt(Numpepsi.getText());
                        Num8 = Num * 40;
                        point += 30;
                    }

                }
            }
            if ((Numwater.getText()).equals("") || !(Numwater.getText()).equals("")) {
                if ((Numwater.getText()).equals("")) {
                    Num9 = 0;
                } else if (!(Numwater.getText()).equals("")) {
                    if ((Numwater.getText()).equals("0")) {
                        Num9 = 0;
                    } else {
                        int Num = Integer.parseInt(Numwater.getText());
                        Num9 = Num * 15;
                        point += 30;
                    }

                }
            }

            total = Num1 + Num2 + Num3 + Num4 + Num5 + Num6 + Num7 + Num8 + Num9;
            jTextField1.setText(total + " ");
            jTextField11.setText(point + " ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try {

            _sql_statment = _connect.createStatement();

            String sql_commnad = "INSERT INTO datachicken (friedchicken,cheesechicken,spicychicken,nuggets,frenchfries,berger,coke,pepsi,drink,total,pointmember,firstname,telephone) VALUES ( '" + Numchick.getText() + "','" + Numcheese.getText() + "','" + NumZeed.getText() + "','" + NumNug.getText() + "','" + Numpotato.getText() + "','" + NumBerger.getText() + "','" + Numcola.getText() + "','" + Numpepsi.getText() + "','" + Numwater.getText() + "','" + jTextField1.getText() + "','" + jTextField11.getText() + "','" + Name.getText() + "','" + telephone1.getText() + "') ";
            _sql_statment.execute(sql_commnad);
            System.out.println("save data complete");
            //ถ้าแต้มถึงให้ลิงค์ไปหน้าcheckpro
 
            
        if (Integer.parseInt(Allpoint.getText()) < 300) {
            System.out.println(Integer.parseInt(Allpoint.getText()));            
             suc1 Suc = new suc1();
            String total2 = Double.toString(total);
            Suc.price.setText(total2);
            
            
           //ส่งรายการอาหาร
        Suc.setVisible(true);


        if (!(Numchick.getText()).equals("0")) {
            String data[] = {"ไก่ทอด", Numchick.getText(), "60", String.format("%d", (Integer.parseInt(Numchick.getText())) * 60)};
            DefaultTableModel tbm1 = (DefaultTableModel) Suc.jTable1.getModel();
            tbm1.addRow(data);
        }
        if (!(Numcheese.getText()).equals("0")) {
            String data[] = {"ไก่ชีส", Numcheese.getText(), "100", String.format("%d", (Integer.parseInt(Numcheese.getText())) * 100)};
            DefaultTableModel tbm1 = (DefaultTableModel) Suc.jTable1.getModel();
            tbm1.addRow(data);
        }
        if (!(NumZeed.getText()).equals("0")) {
            String data[] = {"ไก่วิ้งแซ่บ", NumZeed.getText(), "80", String.format("%d", (Integer.parseInt(NumZeed.getText())) * 80)};
            DefaultTableModel tbm1 = (DefaultTableModel) Suc.jTable1.getModel();
            tbm1.addRow(data);
        }
        if (!(NumNug.getText()).equals("0")) {
            String data[] = {"นักเก็ตส์", NumNug.getText(), "35", String.format("%d", (Integer.parseInt(NumNug.getText())) * 35)};
            DefaultTableModel tbm1 = (DefaultTableModel) Suc.jTable1.getModel();
            tbm1.addRow(data);
        }
        if (!(Numpotato.getText()).equals("0")) {
            String data[] = {"เฟรนฟราย", Numpotato.getText(), "45", String.format("%d", (Integer.parseInt(Numpotato.getText())) * 45)};
            DefaultTableModel tbm1 = (DefaultTableModel) Suc.jTable1.getModel();
            tbm1.addRow(data);
        }
        if (!(NumBerger.getText()).equals("0")) {
            String data[] = {"เบอร์เกอร์ไก่ทอด", NumBerger.getText(), "79", String.format("%d", (Integer.parseInt(NumBerger.getText())) * 79)};
            DefaultTableModel tbm1 = (DefaultTableModel) Suc.jTable1.getModel();
            tbm1.addRow(data);
        }
        if (!(Numcola.getText()).equals("0")) {
            String data[] = {"โค้ก", Numcola.getText(), "40", String.format("%d", (Integer.parseInt(Numcola.getText())) * 40)};
            DefaultTableModel tbm1 = (DefaultTableModel) Suc.jTable1.getModel();
            tbm1.addRow(data);
        }
        if (!(Numpepsi.getText()).equals("0")) {
            String data[] = {"เป๊ปซี่", Numpepsi.getText(), "40", String.format("%d", (Integer.parseInt(Numpepsi.getText())) * 40)};
            DefaultTableModel tbm1 = (DefaultTableModel) Suc.jTable1.getModel();
            tbm1.addRow(data);
        }
        if (!(Numwater.getText()).equals("0")) {
            String data[] = {"น้ำเปล่า", Numwater.getText(), "15", String.format("%d", (Integer.parseInt(Numwater.getText())) * 15)};
            DefaultTableModel tbm1 = (DefaultTableModel) Suc.jTable1.getModel();
            tbm1.addRow(data);
        }

        Suc.jTable1.setEnabled(false);
        
//        Suc.price.setText();
        Suc.jTable1.getColumnModel().getColumn(0).setPreferredWidth(170);
        Suc.setResizable(false);
        Suc.setVisible(true);
        Suc.pack();
        Suc.setLocationRelativeTo(null);
        setVisible(false);
            
            
            
Suc.setVisible(true);setVisible(false); 
        } else {
            check pro = new check();
            pro.Name1.setText(Name.getText());
             pro.telephone.setText(telephone1.getText());
             pro.totalmon.setText(jTextField1.getText());
            pro.setVisible(true);setVisible(false); 
           // pro.pointused.setText(Allpoint.getText());
            pro.jLabel2.setText(Allpoint.getText());
            int k = Integer.parseInt(Allpoint.getText());
            if (k >= 300) {
                if (k < 500) {

                    pro.pointused.setText("300");
                    pro.percen.setText("5");

                } else if (k >= 500) {
                    pro.percen.setText("10");
                    pro.pointused.setText("500");

                }
            }
        }
        } catch (Exception ex) {
            System.out.println(ex.toString());
            System.out.println("noooooooo data");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
         setDefaultCloseOperation(EXIT_ON_CLOSE);setVisible(false);
    }//GEN-LAST:event_jLabel37MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Allpoint;
    public javax.swing.JLabel Name;
    public static javax.swing.JTextField NumBerger;
    public static javax.swing.JTextField NumNug;
    public static javax.swing.JTextField NumZeed;
    public static javax.swing.JTextField Numcheese;
    public static javax.swing.JTextField Numchick;
    public static javax.swing.JTextField Numcola;
    public static javax.swing.JTextField Numpepsi;
    public static javax.swing.JTextField Numpotato;
    public static javax.swing.JTextField Numwater;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField11;
    public javax.swing.JLabel telephone1;
    // End of variables declaration//GEN-END:variables
}
